let stockProductosMates = [
    //Mates
    {
        id:"1",
        nombre:"Mate Buda",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate de buda",
        precio:0000,
        personaje:"Mate cabeza de Buda",
        img:"../multimedia/fotos/productos/Buda.png",
    },
    {
        id:"2",
        nombre:"Mate Pug",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate de cabeza de un perro",
        precio:0000,
        personaje:"Perro de raza Pug",
        img:"../multimedia/fotos/productos/MatePugPerro.jpg",
    },
    {
        id:"3",
        nombre:"Mate Copa Del Mundo",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate de la copa del mundo",
        precio:0000,
        personaje:"Copa del mundo",
        img:"../multimedia/fotos/masVendidos/MateCopaDelMundo.jpg",
    },
    {
        id:"4",
        nombre:"Dragob Ball Z",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate con el simbolo de la escuela de goku",
        precio:0000,
        personaje:"Mate dragon ball Z",
        img:"../multimedia/fotos/productos/MateDragonBall.jpg",
    },
    {
        id:"5",
        nombre:"Elsa",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate de Elsa Frozen",
        precio:0000,
        personaje:"Elsa",
        img:"../multimedia/fotos/productos/mateEslsa.jpg",
    },
    {
        id:"6",
        nombre:"Spiderman",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate cabeza de spiderman",
        precio:0000,
        personaje:"Spiderman",
        img:"../multimedia/fotos/productos/spiderman.jpg",
    },
    {
        id:"7",
        nombre:"Stich Cabeza",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate de la cabeza de stich",
        precio:0000,
        personaje:"stich",
        img:"../multimedia/fotos/productos/MateStich.jpg",
    },
    {
        id:"8",
        nombre:"Baby Yoda",
        tipo:"Mate",
        cantidad:1,
        desc:"Mate cabeza de Baby Yoda",
        precio:0000,
        personaje:"Baby Yoda",
        img:"../multimedia/fotos/productos/mateBabyYoda.jpg",
    },
]